### ISSUE TITLE
One instance of American spelling

### ISSUE THREAD

**Issue by mjsutcliffe99** [zxcalc/book#1]
It's a very minor point but on page 424, it uses the American spelling of "Generalize" (with a "z"), while the rest of the book seems to be using British spellings.

(Also, congrats on finishing the book, it looks great!)

**Comment by mjsutcliffe99** [comment]
Also "minimize" on page 434

**Comment by mjsutcliffe99** [comment]
After noticing the above I've since been on a little search and found...

"Artifact" rather than "artefact" on page 155?

Possibly also "donut" rather than "doughnut"(?) (x2) on page 545?

**Comment by jvdwetering** [comment]
Artifact seems to be quite accepted in British spelling as well, so I don't think we will change that. Donut vs doughnut seems to be more of an old-timey vs new way of writing instead of British vs American.

**Comment by mjsutcliffe99** [comment]
That makes sense, I wasn't too sure about those last two anyway (except I think I saw artifact/artefact spelled both ways at different points in book, so that was more a point of consistency). I think I saw "energizing" somewhere as well? But those are all I could find, the rest looks good! :)

**Comment by jvdwetering** [comment]
Fixed the issues mentioned here in v1.1.0.
